#!/bin/sh

# Specify the directory for the hooks.
# We'll use the current one (.githooks)
hookDir="$(dirname $0)/../"


function hadolint() {
	dockerfile=$1
	echo "Executing hadolint against ${dockerfile} ..."
	docker run --rm hadolint/hadolint < ${dockerfile}
	if (($?)); then
		echo "ERROR: hadolint: ${dockerfile}. Aborting commit"
		exit 1
	fi
}


function dockerfilelint() {
	dockerfile=$1
	echo "Executing dockerfile-lint against ${dockerfile} ..."
	docker run --rm --privileged -v $PWD:/root/ projectatomic/dockerfile-lint dockerfile_lint -f ${dockerfile}
	if (($?)); then
		echo "ERROR: dockerfile-lint: ${dockerfile}. Aborting commit"
		exit 1
	fi
}

function generate_dockerfiles() {
	ansible-playbook site.yml -D
	if (($?)); then
		echo "ERROR: generate_dockerfiles with ansible. Aborting commit"
		exit 1
	fi
}

### Main
echo "Starting pre-commit build sequence..."
generate_dockerfiles

echo "Starting pre-commit validation sequence..."
for dockerfile in *Dockerfile; do
	
	hadolint ${dockerfile}
	dockerfilelint ${dockerfile}
done

