#!/bin/bash


BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
VCS_REF=`git rev-parse --short HEAD`

echo "Build hook running"
echo "Build ${VCS_REF} tag"
docker build --build-arg BUILD_DATE=${BUILD_DATE} \
             --build-arg VCS_REF=${VCS_REF} \
             --build-arg DOCKER_REPO=${DOCKER_REPO} \
             --build-arg DOCKER_TAG=${VCS_REF} \
             -t $DOCKER_REPO:${VCS_REF} .

echo "Tag latest"
docker tag $DOCKER_REPO:${VCS_REF} $DOCKER_REPO:latest

echo "Build debug tag"
docker build --build-arg BUILD_DATE=${BUILD_DATE} \
             --build-arg VCS_REF=${VCS_REF} \
             --build-arg DOCKER_REPO=${DOCKER_REPO} \
             --build-arg DOCKER_TAG=debug \
             -f debug.Dockerfile \
             -t $DOCKER_REPO:debug .
